# Generated by Django 5.2.8 on 2026-09-02 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_workspace_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='board_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
